// Code generated by protoc-gen-go.
// source: github.com/kazoup/ldap-srv/proto/ldap.proto
// DO NOT EDIT!

/*
Package ldap is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/ldap-srv/proto/ldap.proto

It has these top-level messages:
	Config
	CreateRequest
	CreateResponse
*/
package ldap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Config struct {
	BaseDn       string   `protobuf:"bytes,1,opt,name=base_dn" json:"base_dn,omitempty"`
	Host         string   `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port         uint32   `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	UseSsl       bool     `protobuf:"varint,4,opt,name=use_ssl" json:"use_ssl,omitempty"`
	BindDn       string   `protobuf:"bytes,5,opt,name=bind_dn" json:"bind_dn,omitempty"`
	BindPassword string   `protobuf:"bytes,6,opt,name=bind_password" json:"bind_password,omitempty"`
	UserFilter   string   `protobuf:"bytes,7,opt,name=user_filter" json:"user_filter,omitempty"`
	GroupFilter  string   `protobuf:"bytes,8,opt,name=group_filter" json:"group_filter,omitempty"`
	Attr         []string `protobuf:"bytes,9,rep,name=attr" json:"attr,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Config *Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LDAP service

type LDAPClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
}

type lDAPClient struct {
	c           client.Client
	serviceName string
}

func NewLDAPClient(serviceName string, c client.Client) LDAPClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "ldap"
	}
	return &lDAPClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *lDAPClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "LDAP.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LDAP service

type LDAPHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
}

func RegisterLDAPHandler(s server.Server, hdlr LDAPHandler) {
	s.Handle(s.NewHandler(&LDAP{hdlr}))
}

type LDAP struct {
	LDAPHandler
}

func (h *LDAP) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.LDAPHandler.Create(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x09, 0x0d, 0x49, 0x33, 0x6d, 0x5a, 0x64, 0x40, 0x58, 0xac, 0xaa, 0xac, 0x22, 0x55,
	0x38, 0x52, 0x7b, 0x02, 0x54, 0x96, 0x2c, 0x10, 0x17, 0xa8, 0x9c, 0xc6, 0x4d, 0x23, 0x42, 0x6c,
	0x3c, 0x0e, 0x48, 0x5c, 0x88, 0x6b, 0xe2, 0x0e, 0xca, 0x22, 0x3b, 0xff, 0xe7, 0xff, 0xed, 0x3f,
	0x03, 0xeb, 0xba, 0x71, 0xa7, 0xbe, 0x14, 0x07, 0xfd, 0x51, 0xbc, 0xcb, 0x1f, 0xdd, 0x9b, 0xa2,
	0xad, 0xa4, 0x79, 0x44, 0xfb, 0x55, 0x18, 0xab, 0x9d, 0x26, 0x29, 0xe8, 0x98, 0xfd, 0x06, 0x10,
	0xed, 0x74, 0x77, 0x6c, 0x6a, 0xb6, 0x84, 0xb8, 0x94, 0xa8, 0xf6, 0x55, 0xc7, 0x83, 0x55, 0x90,
	0x27, 0x6c, 0x0e, 0xe1, 0x49, 0xa3, 0xe3, 0x97, 0x83, 0x32, 0xda, 0x3a, 0x3e, 0xf1, 0x2a, 0x3d,
	0x9b, 0x7b, 0xef, 0x45, 0x6c, 0x79, 0xe8, 0xc1, 0x94, 0xd2, 0x4d, 0x57, 0x9d, 0xd3, 0x57, 0xe4,
	0xbf, 0x83, 0x94, 0x80, 0x91, 0x88, 0xdf, 0xda, 0x56, 0x3c, 0x22, 0x7c, 0x03, 0x33, 0x1f, 0xb4,
	0xfb, 0x63, 0xd3, 0x3a, 0x65, 0x79, 0x4c, 0xf0, 0x16, 0xe6, 0xb5, 0xf5, 0x45, 0x07, 0x3a, 0x1d,
	0x7e, 0x94, 0xce, 0x59, 0x9e, 0xac, 0x26, 0x79, 0x92, 0xe5, 0x90, 0xee, 0xac, 0x92, 0x4e, 0xbd,
	0xa9, 0xcf, 0x5e, 0xa1, 0x63, 0xf7, 0x10, 0x1d, 0xa8, 0x39, 0xd5, 0x9d, 0x6d, 0x62, 0xf1, 0x3f,
	0x48, 0x76, 0x0d, 0x8b, 0xc1, 0x89, 0x46, 0x77, 0xa8, 0x36, 0x5b, 0x08, 0x5f, 0x9e, 0x9f, 0x5e,
	0xd9, 0xda, 0x0f, 0x4b, 0x37, 0x6c, 0x21, 0x46, 0x8f, 0x3d, 0x2c, 0xc5, 0x38, 0x92, 0x5d, 0x94,
	0x11, 0x6d, 0x68, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x58, 0xad, 0x16, 0xbd, 0x50, 0x01, 0x00,
	0x00,
}
